import type Project from "@/types/project";

const projectsData: Project[] = [
	{
		title: "Marker",
		slug: "marker",
		role: "Development",
		url: "https://marker.sk",
		color: "green",
		year: "2025",
		active: true,
	},
	{
		title: "Mafert",
		slug: "mafert",
		role: "Development",
		url: "https://mafert.sk",
		color: "red",
		year: "2025",
	},
	{
		title: "Legro",
		slug: "legro",
		role: "Development",
		url: "https://legro.sk",
		color: "red",
		year: "2025",
	},
	{
		title: "Audilun",
		slug: "audilun",
		role: "Development",
		url: "https://audilun.com",
		color: "lime-green",
		year: "2025",
	},
	{
		title: "Racetime",
		slug: "racetime",
		role: "Development & Design",
		url: "https://racetime.sk",
		color: "red",
		wip: true,
		year: "2025",
	},
	{
		title: "Bavimi",
		slug: "bavimi",
		role: "Template Customization",
		url: "https://bavimi.sk",
		color: "yellow",
		year: "2025",
	},
	{
		title: "Hypur",
		slug: "hypur",
		role: "Development & Design",
		url: "https://hypur.sk",
		color: "sky-blue",
		wip: true,
		year: "2025",
	},
	{
		title: "STUDIO PARADA",
		slug: "studio-parada",
		role: "Development",
		url: "https://studioparada.com",
		color: "gray",
		year: "2024",
	},
	{
		title: "Volita",
		slug: "volita",
		role: "Development & Design",
		url: "https://volita.sk",
		color: "sky-blue",
		year: "2023",
	},
	{
		title: "TESTAR",
		slug: "testar",
		role: "Development & Design",
		url: "https://testar.sk",
		color: "blue",
		year: "2022",
	},
	{
		title: "Nivy",
		slug: "nivy",
		role: "Optimization & Refactoring",
		url: "https://nivy.com",
		color: "orange",
		year: "2021",
	},
	{
		title: "ŠARMDENT",
		slug: "sarmdent",
		role: "Development",
		url: "https://sarmdent.sk",
		color: "pink",
		year: "2021",
	},
];

export default projectsData;
